### ISSUE TITLE
Cut up the API methods page

### ISSUE THREAD

**Issue by CptMayday** [saasquatch/saasquatch-docs#74] opened 2015-08-04 22:09 UTC
The API methods page (http://docs.referralsaasquatch.com/api/methods) is getting really long and doesn't load properly. It's probably better to cut it up to multiple pages or optimize it somehow.

**Comment by loganvolkers** [comment] 2015-09-21 06:08
Duplicate of #57

**Closed as completed** 2015-09-21 06:09 UTC
Labels: duplicate, enhancement
